optionsMap = {
		"print.layer.height.first": "first_layer_height",
		"print.layer.height.other": "layer_height",
		"print.speed.perimeters": "perimeter_speed",
		"print.speed.small-perimeters": "small_perimeter_speed",
		"print.speed.external-perimeters": "external_perimeter_speed",
		"print.speed.infill": "infill_speed",
		"print.speed.solid-infill": "solid_infill_speed",
		"print.speed.top-solid-infill": "top_solid_infill_speed",
		"print.speed.support-material": "support_material",
		"print.speed.support-material-interface": "support_material_interface_speed",
		"print.speed.bridges": "bridge_speed",
		"print.speed.gap-fill": "gap_fill_speed",
		"print.speed.travel": "travel_speed",
		"print.speed.first-layer-speed": "first_layer_speed",
		"print.layer.vertical-shells.perimeters": "perimeters",
		"print.layer.vertical-shells.spiral-vase": "spiral_vase",
		"print.layer.horizontal-shells.solid-layers-top": "top_solid_layers",
		"print.layer.horizontal-shells.solid-layers-bottom": "bottom_solid_layers",
		"print.layer.quality.extra-perimeters": "extra_perimeters",
		"print.layer.quality.avoid-crossing-perimeters": "avoid_crossing_perimeters",
		"print.layer.quality.detect-thin-walls": "thin_walls",
		"print.layer.quality.detect-bridging-perimeters": "overhangs",
		"print.layer.advanced.seam-position": "seam_position",
		"print.layer.advanced.external-perimeters-first": "external_perimeters_first",
		
		"printer.bed-size": "bed_size",
		"printer.print-center": "print_center",
		"printer.z-offset": "z_offset",
		"extruder.nozzle-diameter": "nozzle_diameter",
		"extruder.retraction.length": "retract_length",
		"extruder.retraction.lift-z": "retract_lift",
		"extruder.retraction.speed": "retract_speed",

		"gcode.start": "start_gcode",
		"gcode.end": "end_gcode",
}
